name: gsplat
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - tqdm
  - psutil
  - pandas
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
      - submodules/gsplat

